name: "Principal Container Builder Pipeline - lamusmaser"
description: "The principal container builder pipeline for lamusmaser. For referencing in the other projects that need a pipeline to test and build a container."

inputs:
  DH_REGISTRY: 
    description: "DockerHub Registry"
    default: "docker.io"
    required: true
  DH_USERNAME:  
    description: "DockerHub Username"
    required: true
  DH_PASSWORD:  
    description: "DockerHub Password"
    required: true
  GH_REGISTRY:  
    description: "GitHub Registry"
    default: "ghcr.io"
    required: true
  GH_USERNAME:  
    description: "GitHub Username"
    required: true
  GH_PAT:  
    description: "GitHub PAT"
    required: true
  IMAGE_NAME:  
    description: "Image Name of the container"
    required: true
  PLATFORMS:  
    description: "Platforms for which to build the container"
    default: "linux/arm64/v8,linux/amd64"
    required: true

runs:
  using: "composite"
  steps:
    # Example of how to call this action from another repository
    # name: Build and Push Docker Image
    # uses: lamusmaser/principal_container_builder_pipeline@v1
    # with:
    #   DH_REGISTRY: ${{ secrets.DH_REGISTRY }}
    #   DH_USERNAME: ${{ secrets.DH_USERNAME }}
    #   DH_PASSWORD: ${{ secrets.DH_PASSWORD }}
    #   GH_REGISTRY: ${{ secrets.GH_REGISTRY }}
    #   GH_USERNAME: ${{ secrets.GH_USERNAME }}
    #   GH_PAT: ${{ secrets.GH_PAT }}
    #   IMAGE_NAME: my-image
    #   PLATFORMS: linux/arm64/v8,linux/amd64

    # Step 1: Linting/Testing
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      shell: bash
      run: pytest

    # Step 2: Container Build Test
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.DH_USERNAME }}
        password: ${{ inputs.DH_PASSWORD }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ inputs.GH_REGISTRY }}
        username: ${{ inputs.GH_USERNAME }}
        password: ${{ inputs.GH_PAT }}

    - name: Build Docker image for testing
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: |
          ${{ inputs.DH_REGISTRY }}/${{ inputs.DH_USERNAME }}/${{ inputs.IMAGE_NAME }}:test
        platforms: ${{ inputs.PLATFORMS }}

    # Step 3: Container Build and Push
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{ inputs.DH_REGISTRY }}/${{ inputs.DH_USERNAME }}/${{ inputs.IMAGE_NAME }}:latest
          ${{ inputs.GH_REGISTRY }}/${{ inputs.GH_USERNAME }}/${{ inputs.IMAGE_NAME }}:latest
        platforms: ${{ inputs.PLATFORMS }}